### ISSUE TITLE
Overlay Plugin과 충돌 문제가 있습니다.

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [Elysia-ff/FFXIV_DiscordPresence#1]
https://github.com/ngld/OverlayPlugin 이 오버레이 플러그인과의 충돌 문제가 있는데, 

이 플러그인과 저 플러그인을 동시에 사용하면
Overlay Plugin의 컷신 이벤트 중에 숨기는 기능이 작동하지 않습니다.
![K-003](https://user-images.githubusercontent.com/4695371/95460941-91351000-09b0-11eb-881d-a7a9f076d1fa.png)

### 증상 확인을 위해 시도해본 것들
1. Overlay Plugin 순서를 맨 뒤로 놓기
Overlay Plugin 로드 순서와는 상관 없이 항상 같은 문제가 발생했습니다.

2. Overlay Plugin 해제 후 다시 enable 하기
ACT 실행이 완료된 후(모든 플러그인 로드가 완료), Overlay Plugin을 해제하고 다시 enable하면 해당 컷신 중 숨기기 기능이 제대로 작동합니다.

3. 원인 확인, 이 플러그인을 해제해봤습니다.
이 플러그인을 disable하면 컷신 중 숨기기 기능이 잘 작동합니다.

* 참고로 overlay plugin 제거 후 최신 릴리즈로 다시 설치해도 동일한 문제가 발생했습니다.

**Comment by Elysia-ff** [comment]
웹소켓만 사용하다보니 전혀 몰랐네요 ㅠㅠ
수정했습니다. 글로벌서버에서 테스트했어요!
